#!/bin/bash
sudo apt-get install kodi kodi-peripheral-joystick kodi-pvr-iptvsimple kodi-inputstream-adaptive kodi-inputstream-rtmp kodi-vfs-libarchive kodi-vfs-nfs kodi-vfs-sftp
sudo sh -c "echo 'start_x=1' >> /boot/config.txt"

echo '/home/pi/pi_scripts/autostart' >> ~/.bashrc
