#!/bin/bash
wget -q -O - https://apt.mopidy.com/mopidy.gpg | sudo apt-key add -
sudo wget -q -O /etc/apt/sources.list.d/mopidy.list https://apt.mopidy.com/buster.list
sudo apt update
sudo apt install mopidy mopidy-local python3-pip
sudo python3 -m pip install Mopidy-Iris
sudo sh -c 'cat /home/pi/pi_scripts/mopidy.conf > /etc/mopidy/mopidy.conf'
sudo systemctl enable mopidy
