#!/bin/bash
if ls ~/nas | grep -q movies_; then
    curl --data-binary '{ "jsonrpc": "2.0", "method": "VideoLibrary.Scan", "id": "mybash"}' -H 'content-type: application/json;' "http://kodi:kodi42@localhost:8080/jsonrpc"
fi
