#!/bin/bash
LOG_DIR=/home/pi/logs
TIMEST=$(date -u +"%Y-%m-%d")
LOG_FILE="${LOG_DIR}/mopidy-${TIMEST}.log"

if ! whoami | grep -q 'root'; then
    mkdir -p "${LOG_DIR}"
	sudo /home/pi/pi_scripts/mopidy_update || exit 1
    exit 0
fi

mop_output=$(mopidyctl local scan --limit 2000)
echo ${mop_output} >> "${LOG_FILE}"
