#!/bin/bash
LOG_DIR=/home/pi/logs
TIMEST=$(date -u +"%Y-%m-%d")
LOG_FILE="${LOG_DIR}/mopidy-${TIMEST}.log"

mkdir -p "${LOG_DIR}"

if ! whoami | grep -q 'root'; then
	sudo /home/pi/pi_scripts/mopidy_update || exit 1
    exit 0
fi

mopidyctl local scan --limit 2000 >> "${LOG_FILE}"
